name: backend



on:
  push:
    branches: [ "master" ]


    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]
 
    

jobs:
      
      
      
  docker:
  

    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: docker build
         run: docker build . --file Dockerfile --tag bs2backend:latest
