name: backend



on:
  push:
    branches: [ "master" ]


    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]
 
    

jobs:
      
      
      
  docker:
  

    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: docker build
         run: docker build . --file Dockerfile --tag bs2backend:latest
         
         
  webhook:
    needs: docker
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: curl -X POST http://193.191.176.62:9000/api/webhooks/db6c73e0-8341-4c28-8d2f-9ad7268ee075
